# Generated by Django 4.1.1 on 2022-12-03 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myBonus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilegehistorymodel',
            name='ticket_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
