# Generated by Django 4.1.1 on 2022-11-19 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=80)),
                ('flight_number', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('CANCELED', 'Canceled')], max_length=20)),
            ],
        ),
    ]
