name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt


      - name: Run tests, makemigrations, migrate
        run: |
          python3 manage.py test --keepdb 
          python3 manage.py makemigrations
          python3 manage.py migrate


      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
            heroku_api_key: ${{secrets.API_KEY_FOR_HEROKU}}
            heroku_app_name: ${{secrets.APP_NAME_IN_HEROKU}}
            heroku_email: ${{secrets.EMAIL_FOR_HEROKU}}
            usedocker: true

      - name: Let's wait
        run: sleep 30

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'


      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true


      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"